import type { Category, FaqItem, Scholarship } from "./types";

/**
 * MOCK DATA NOTICE
 * ------------------------------------------------------------------
 * Everything in this file is illustrative placeholder content used to
 * power the UI while there is no backend. Names of well-known scholarship
 * programs are used for realism, but deadlines, figures, and descriptions
 * below are fictionalized for demo purposes and should NOT be treated as
 * accurate/live information. Replace this file with real API calls once
 * a backend (e.g. Supabase) is connected.
 * ------------------------------------------------------------------
 */

export const scholarships: Scholarship[] = [
  {
    id: "1",
    slug: "chevening-scholarship-uk",
    name: "Chevening Scholarship",
    provider: "UK Government (FCDO)",
    university: "Any UK University",
    country: "United Kingdom",
    region: "Europe",
    degreeLevels: ["Masters"],
    fieldsOfStudy: ["Any Field"],
    fundingType: "Fully Funded",
    fundingDetails: "Tuition, living stipend, flights, and visa costs covered",
    deadline: "2026-11-02",
    postedDate: "2026-06-01",
    popularity: 98,
    description:
      "A global award scheme funded by the UK government, offering future leaders the chance to pursue a one-year master's degree at any UK university.",
    eligibility: [
      "Nigerian citizen with a first degree",
      "Minimum 2 years of work experience",
      "Return to Nigeria for at least 2 years after the award",
    ],
    applicationProcess: [
      "Create an account on the Chevening portal",
      "Submit personal statement and essays",
      "Receive up to 3 UK university offers",
      "Attend an interview at the British High Commission",
    ],
    requiredDocuments: ["International passport", "Degree certificate", "Two references", "Essays"],
    officialUrl: "https://www.chevening.org",
    categories: ["masters", "fully-funded", "international"],
    tags: ["Trending", "Fully Funded"],
    logoInitials: "CH",
  },
  {
    id: "2",
    slug: "mastercard-foundation-scholars",
    name: "Mastercard Foundation Scholars Program",
    provider: "Mastercard Foundation",
    university: "University of Cape Town, Univ. of Toronto, Univ. of Edinburgh & partners",
    country: "Multiple Countries",
    region: "Africa",
    degreeLevels: ["Undergraduate", "Masters"],
    fieldsOfStudy: ["STEM", "Business", "Social Sciences"],
    fundingType: "Fully Funded",
    fundingDetails: "Full tuition, accommodation, stipend, mentorship, and leadership training",
    deadline: "2026-09-15",
    postedDate: "2026-05-10",
    popularity: 95,
    description:
      "Supports academically talented but economically disadvantaged young Africans to access quality, relevant higher education and become leaders driving change.",
    eligibility: [
      "Nigerian citizen under 29 years",
      "Demonstrated financial need",
      "Strong academic record",
      "Commitment to giving back to Africa",
    ],
    applicationProcess: [
      "Apply directly through partner university admissions",
      "Indicate Mastercard Foundation Scholars interest",
      "Complete leadership and community essays",
      "Shortlisting and interview",
    ],
    requiredDocuments: ["Transcripts", "Financial need statement", "Recommendation letters"],
    officialUrl: "https://mastercardfdn.org/all/scholars/",
    categories: ["undergraduate", "masters", "fully-funded", "international", "women", "stem"],
    tags: ["Fully Funded", "Trending"],
    logoInitials: "MF",
  },
  {
    id: "3",
    slug: "daad-eposcholarship-germany",
    name: "DAAD EPOS Scholarship",
    provider: "German Academic Exchange Service",
    university: "Various German Universities",
    country: "Germany",
    region: "Europe",
    degreeLevels: ["Masters", "PhD"],
    fieldsOfStudy: ["Development Studies", "Engineering", "Public Policy"],
    fundingType: "Fully Funded",
    fundingDetails: "Monthly stipend, health insurance, and travel allowance",
    deadline: "2026-08-30",
    postedDate: "2026-04-20",
    popularity: 80,
    description:
      "Supports graduates from developing countries pursuing postgraduate studies relevant to development-related fields in Germany.",
    eligibility: ["Bachelor's degree with above-average grades", "At least 2 years of professional experience"],
    applicationProcess: ["Apply via uni-assist or directly to program", "Submit letter of motivation", "Language proficiency proof"],
    requiredDocuments: ["CV", "Motivation letter", "Language certificate (English/German)"],
    officialUrl: "https://www.daad.de",
    categories: ["masters", "phd", "fully-funded", "international", "research"],
    tags: ["Fully Funded"],
    logoInitials: "DA",
  },
  {
    id: "4",
    slug: "commonwealth-shared-scholarship",
    name: "Commonwealth Shared Scholarship",
    provider: "UK Commonwealth Scholarship Commission",
    university: "Various UK Universities",
    country: "United Kingdom",
    region: "Europe",
    degreeLevels: ["Masters"],
    fieldsOfStudy: ["Development-related fields"],
    fundingType: "Fully Funded",
    fundingDetails: "Airfare, tuition fees, and living stipend for shared study",
    deadline: "2026-12-10",
    postedDate: "2026-06-15",
    popularity: 76,
    description:
      "For students from developing Commonwealth countries who would not otherwise be able to study in the UK, to pursue a taught master's degree.",
    eligibility: ["Citizen of a developing Commonwealth country", "First degree with at least second class upper"],
    applicationProcess: ["Apply through the Commonwealth Scholarship portal", "Await nomination from CSC"],
    requiredDocuments: ["Academic transcripts", "Two reference letters", "Research proposal (if applicable)"],
    officialUrl: "https://cscuk.fcdo.gov.uk",
    categories: ["masters", "fully-funded", "international"],
    tags: ["Closing Soon"],
    logoInitials: "CS",
  },
  {
    id: "5",
    slug: "australia-awards-scholarship",
    name: "Australia Awards Scholarship",
    provider: "Australian Government (DFAT)",
    university: "Various Australian Universities",
    country: "Australia",
    region: "Oceania",
    degreeLevels: ["Masters", "PhD"],
    fieldsOfStudy: ["Agriculture", "Public Health", "Economics"],
    fundingType: "Fully Funded",
    fundingDetails: "Full tuition, living allowance, health cover, and return airfare",
    deadline: "2027-01-31",
    postedDate: "2026-06-20",
    popularity: 68,
    description:
      "Long-term development scholarships administered by the Australian Government to contribute to the development needs of Nigeria.",
    eligibility: ["Nigerian citizen", "Minimum of 2 years relevant work experience", "Meet English language requirements"],
    applicationProcess: ["Complete OASIS online application", "Submit supporting documents", "Interview if shortlisted"],
    requiredDocuments: ["IELTS/TOEFL score", "Academic transcripts", "Employment reference"],
    officialUrl: "https://www.dfat.gov.au/people-to-people/australia-awards",
    categories: ["masters", "phd", "fully-funded", "international"],
    tags: ["New"],
    logoInitials: "AA",
  },
  {
    id: "6",
    slug: "ptdf-overseas-scholarship-nigeria",
    name: "PTDF Overseas Scholarship Scheme",
    provider: "Petroleum Technology Development Fund",
    university: "Selected Universities in UK, France & Malaysia",
    country: "Nigeria",
    region: "Nigeria",
    degreeLevels: ["Masters", "PhD"],
    fieldsOfStudy: ["Engineering", "Geosciences", "Energy"],
    fundingType: "Fully Funded",
    fundingDetails: "Tuition, upkeep allowance, and book allowance",
    deadline: "2026-08-05",
    postedDate: "2026-05-01",
    popularity: 71,
    description:
      "A Nigerian federal government scheme sponsoring postgraduate studies in oil and gas related disciplines for Nigerian students.",
    eligibility: ["Nigerian citizen", "Minimum second class upper degree", "Not above 35 years for MSc"],
    applicationProcess: ["Apply via PTDF portal", "Sit for aptitude test", "Attend interview"],
    requiredDocuments: ["NYSC certificate", "Degree certificate", "Local government identification"],
    officialUrl: "https://ptdf.gov.ng",
    categories: ["nigeria", "masters", "phd", "fully-funded", "stem"],
    tags: ["Trending"],
    logoInitials: "PT",
  },
  {
    id: "7",
    slug: "erasmus-mundus-joint-masters",
    name: "Erasmus Mundus Joint Master Degree",
    provider: "European Commission",
    university: "Consortium of European Universities",
    country: "European Union",
    region: "Europe",
    degreeLevels: ["Masters"],
    fieldsOfStudy: ["Data Science", "Environmental Science", "International Relations"],
    fundingType: "Fully Funded",
    fundingDetails: "Tuition waiver plus monthly stipend across 2+ countries",
    deadline: "2026-11-20",
    postedDate: "2026-06-05",
    popularity: 84,
    description:
      "A prestigious, integrated international study programme delivered by a consortium of universities across at least two European countries.",
    eligibility: ["Bachelor's degree in a relevant field", "English proficiency"],
    applicationProcess: ["Choose a joint master's program", "Apply through consortium portal", "Rank preferred host countries"],
    requiredDocuments: ["Transcripts", "Motivation letter", "CV (Europass format)"],
    officialUrl: "https://www.eacea.ec.europa.eu",
    categories: ["masters", "fully-funded", "international", "exchange-programs"],
    tags: ["New", "Fully Funded"],
    logoInitials: "EM",
  },
  {
    id: "8",
    slug: "schlumberger-faculty-for-future",
    name: "Schlumberger Faculty for the Future Fellowship",
    provider: "Schlumberger Foundation",
    university: "Top Global Universities",
    country: "Multiple Countries",
    region: "North America",
    degreeLevels: ["PhD", "Postdoctoral"],
    fieldsOfStudy: ["STEM"],
    fundingType: "Fully Funded",
    fundingDetails: "Grants covering tuition and a living stipend for women in STEM",
    deadline: "2026-12-31",
    postedDate: "2026-06-18",
    popularity: 65,
    description:
      "Grants to women from developing countries pursuing PhD or post-doctoral studies in STEM disciplines at top universities abroad.",
    eligibility: ["Woman with admission (or pending admission) to a PhD program", "Intention to return home country to teach"],
    applicationProcess: ["Online application with research proposal", "Reference letters", "Panel review"],
    requiredDocuments: ["Research proposal", "University admission letter", "CV"],
    officialUrl: "https://www.fftf.slb.com",
    categories: ["phd", "fully-funded", "women", "stem", "research"],
    tags: ["Trending"],
    logoInitials: "SF",
  },
  {
    id: "9",
    slug: "unilag-undergraduate-merit-award",
    name: "UNILAG Vice-Chancellor's Merit Award",
    provider: "University of Lagos",
    university: "University of Lagos",
    country: "Nigeria",
    region: "Nigeria",
    degreeLevels: ["Undergraduate"],
    fieldsOfStudy: ["Any Field"],
    fundingType: "Partial Funding",
    fundingDetails: "50% tuition waiver for top-performing students",
    deadline: "2026-09-01",
    postedDate: "2026-06-10",
    popularity: 58,
    description:
      "Awarded to indigent but academically outstanding undergraduate students at the University of Lagos each session.",
    eligibility: ["Current UNILAG student", "CGPA of 4.5 and above", "Demonstrated financial need"],
    applicationProcess: ["Apply through the Student Affairs office", "Submit academic transcript", "Departmental endorsement"],
    requiredDocuments: ["Current transcript", "Financial need declaration"],
    officialUrl: "https://unilag.edu.ng",
    categories: ["nigeria", "undergraduate"],
    tags: ["New"],
    logoInitials: "UL",
  },
  {
    id: "10",
    slug: "korea-government-scholarship-gks",
    name: "Global Korea Scholarship (GKS)",
    provider: "Government of South Korea (NIIED)",
    university: "Various Korean Universities",
    country: "South Korea",
    region: "Asia",
    degreeLevels: ["Undergraduate", "Masters", "PhD"],
    fieldsOfStudy: ["Any Field"],
    fundingType: "Fully Funded",
    fundingDetails: "Airfare, tuition, monthly allowance, and Korean language training",
    deadline: "2027-02-15",
    postedDate: "2026-06-25",
    popularity: 90,
    description:
      "One of the most generous fully funded scholarships, sponsoring international students to study at Korean universities across all degree levels.",
    eligibility: ["Under 25 (undergrad) / 40 (postgrad)", "GPA of 80% or higher", "Good health"],
    applicationProcess: ["Apply via Korean Embassy or university track", "Submit study plan", "Interview at Embassy"],
    requiredDocuments: ["Study plan", "Health certificate", "Academic transcripts"],
    officialUrl: "https://www.studyinkorea.go.kr",
    categories: ["undergraduate", "masters", "phd", "fully-funded", "international"],
    tags: ["Trending", "Fully Funded"],
    logoInitials: "GK",
  },
  {
    id: "11",
    slug: "fulbright-foreign-student-program",
    name: "Fulbright Foreign Student Program",
    provider: "US Department of State",
    university: "Various US Universities",
    country: "United States",
    region: "North America",
    degreeLevels: ["Masters", "PhD"],
    fieldsOfStudy: ["Any Field"],
    fundingType: "Fully Funded",
    fundingDetails: "Tuition, living stipend, health insurance, and travel",
    deadline: "2026-10-05",
    postedDate: "2026-06-02",
    popularity: 88,
    description:
      "Enables graduate students to conduct research and earn master's or PhD degrees at US institutions, fostering mutual understanding.",
    eligibility: ["Nigerian citizen", "Bachelor's degree", "Strong leadership potential"],
    applicationProcess: ["Apply via US Embassy Public Affairs Section", "Standardized test scores", "Written essays and interview"],
    requiredDocuments: ["GRE/TOEFL scores", "Statement of purpose", "Academic records"],
    officialUrl: "https://ng.usembassy.gov",
    categories: ["masters", "phd", "fully-funded", "international", "research"],
    tags: ["Trending"],
    logoInitials: "FB",
  },
  {
    id: "12",
    slug: "african-union-nepad-scholarship",
    name: "AU-NEPAD STI Scholarship",
    provider: "African Union / NEPAD",
    university: "Pan-African University Institutes",
    country: "Multiple African Countries",
    region: "Africa",
    degreeLevels: ["Masters", "PhD"],
    fieldsOfStudy: ["Science", "Technology", "Innovation"],
    fundingType: "Fully Funded",
    fundingDetails: "Tuition, monthly stipend, and research grant",
    deadline: "2026-09-25",
    postedDate: "2026-05-28",
    popularity: 54,
    description:
      "Supports African students pursuing postgraduate studies in science, technology, and innovation at Pan-African University institutes.",
    eligibility: ["Citizen of an African Union member state", "Relevant Bachelor's or Master's degree"],
    applicationProcess: ["Apply through PAU institute portal", "Submit research interest statement"],
    requiredDocuments: ["Degree certificates", "Statement of purpose", "Two references"],
    officialUrl: "https://pau-au.africa",
    categories: ["masters", "phd", "fully-funded", "international", "stem", "research"],
    tags: ["New"],
    logoInitials: "AU",
  },
  {
    id: "13",
    slug: "japan-mext-scholarship",
    name: "MEXT Scholarship",
    provider: "Government of Japan",
    university: "Various Japanese Universities",
    country: "Japan",
    region: "Asia",
    degreeLevels: ["Undergraduate", "Masters", "PhD"],
    fieldsOfStudy: ["Any Field"],
    fundingType: "Fully Funded",
    fundingDetails: "Full tuition, monthly stipend of approx. ¥143,000-145,000, and round-trip airfare",
    deadline: "2026-08-15",
    postedDate: "2026-04-15",
    popularity: 73,
    description:
      "Japan's Ministry of Education scholarship covering full study costs for international students at Japanese universities.",
    eligibility: ["Under 35 years old (varies by degree)", "Good academic standing", "Willingness to learn Japanese"],
    applicationProcess: ["Apply via Japanese Embassy", "Sit for written exams", "Interview"],
    requiredDocuments: ["Academic transcripts", "Health certificate", "Recommendation letter"],
    officialUrl: "https://www.ng.emb-japan.go.jp",
    categories: ["undergraduate", "masters", "phd", "fully-funded", "international"],
    tags: ["Closing Soon"],
    logoInitials: "MX",
  },
  {
    id: "14",
    slug: "gates-cambridge-scholarship",
    name: "Gates Cambridge Scholarship",
    provider: "Bill & Melinda Gates Foundation",
    university: "University of Cambridge",
    country: "United Kingdom",
    region: "Europe",
    degreeLevels: ["Masters", "PhD"],
    fieldsOfStudy: ["Any Field"],
    fundingType: "Fully Funded",
    fundingDetails: "Full cost of studying at Cambridge plus a discretionary stipend",
    deadline: "2026-12-03",
    postedDate: "2026-06-12",
    popularity: 92,
    description:
      "One of the world's most prestigious international scholarships, fully funding outstanding applicants to study any subject at Cambridge.",
    eligibility: ["Non-UK citizen", "Outstanding intellectual ability", "Applying to Cambridge postgraduate course"],
    applicationProcess: ["Apply to Cambridge course + Gates Cambridge together", "Submit research proposal", "Shortlist interview"],
    requiredDocuments: ["Research proposal", "Two academic references", "CV"],
    officialUrl: "https://www.gatescambridge.org",
    categories: ["masters", "phd", "fully-funded", "international", "research"],
    tags: ["Trending", "Fully Funded"],
    logoInitials: "GC",
  },
  {
    id: "15",
    slug: "obama-foundation-africa-leaders",
    name: "Obama Foundation Africa Leaders Program",
    provider: "Obama Foundation",
    university: "Non-degree Leadership Program",
    country: "South Africa / Virtual",
    region: "Africa",
    degreeLevels: ["Exchange"],
    fieldsOfStudy: ["Leadership", "Public Service"],
    fundingType: "Fully Funded",
    fundingDetails: "Program costs, accommodation, and travel fully covered",
    deadline: "2026-08-20",
    postedDate: "2026-05-05",
    popularity: 61,
    description:
      "A leadership development program (not a degree) for young, community-driven changemakers from across Africa.",
    eligibility: ["Age 21-35", "Demonstrated community leadership", "Resident of an African country"],
    applicationProcess: ["Online application with essays", "Video submission", "Panel interview"],
    requiredDocuments: ["Essays", "Proof of community project", "ID document"],
    officialUrl: "https://www.obama.org/africa",
    categories: ["exchange-programs", "international"],
    tags: ["New"],
    logoInitials: "OB",
  },
  {
    id: "16",
    slug: "csc-nigeria-nlng-postgraduate",
    name: "NLNG Postgraduate Scholarship",
    provider: "Nigeria LNG Limited",
    university: "Top Nigerian Universities",
    country: "Nigeria",
    region: "Nigeria",
    degreeLevels: ["Masters", "PhD"],
    fieldsOfStudy: ["Engineering", "Sciences", "Medicine"],
    fundingType: "Fully Funded",
    fundingDetails: "Full tuition and a stipend for local postgraduate study",
    deadline: "2026-10-30",
    postedDate: "2026-06-08",
    popularity: 66,
    description:
      "Supports outstanding Nigerian graduates pursuing postgraduate studies in science and engineering fields within Nigeria.",
    eligibility: ["Nigerian citizen", "First class or strong second class upper", "Admission into a Nigerian university"],
    applicationProcess: ["Apply via NLNG scholarship portal", "Submit admission proof", "Aptitude test"],
    requiredDocuments: ["Admission letter", "Academic transcripts", "NYSC discharge certificate"],
    officialUrl: "https://www.nlng.com",
    categories: ["nigeria", "masters", "phd", "fully-funded", "stem"],
    tags: ["Trending"],
    logoInitials: "NL",
  },
];

export const categories: Category[] = [
  { slug: "undergraduate", name: "Undergraduate", description: "Bachelor's degree scholarships", icon: "GraduationCap", count: scholarships.filter((s) => s.categories.includes("undergraduate")).length },
  { slug: "masters", name: "Masters", description: "Postgraduate master's funding", icon: "BookOpen", count: scholarships.filter((s) => s.categories.includes("masters")).length },
  { slug: "phd", name: "PhD", description: "Doctoral research funding", icon: "Microscope", count: scholarships.filter((s) => s.categories.includes("phd")).length },
  { slug: "fully-funded", name: "Fully Funded", description: "100% cost coverage", icon: "Sparkles", count: scholarships.filter((s) => s.categories.includes("fully-funded")).length },
  { slug: "international", name: "International", description: "Study outside Nigeria", icon: "Globe2", count: scholarships.filter((s) => s.categories.includes("international")).length },
  { slug: "nigeria", name: "Nigeria", description: "Local Nigerian awards", icon: "MapPin", count: scholarships.filter((s) => s.categories.includes("nigeria")).length },
  { slug: "women", name: "Women", description: "For female applicants", icon: "Users", count: scholarships.filter((s) => s.categories.includes("women")).length },
  { slug: "stem", name: "STEM", description: "Science, Tech, Engineering, Math", icon: "FlaskConical", count: scholarships.filter((s) => s.categories.includes("stem")).length },
  { slug: "research", name: "Research", description: "Research-focused grants", icon: "SearchCode", count: scholarships.filter((s) => s.categories.includes("research")).length },
  { slug: "exchange-programs", name: "Exchange Programs", description: "Short-term & leadership exchanges", icon: "ArrowLeftRight", count: scholarships.filter((s) => s.categories.includes("exchange-programs")).length },
];

export const faqs: FaqItem[] = [
  {
    question: "Is ScholarNaija free to use?",
    answer:
      "Yes. Browsing, searching, and saving scholarships on ScholarNaija is completely free for every Nigerian student.",
  },
  {
    question: "Does ScholarNaija guarantee I will get a scholarship?",
    answer:
      "No platform can guarantee an award. ScholarNaija helps you discover relevant, credible opportunities and track deadlines — the application and selection process is handled entirely by each scholarship provider.",
  },
  {
    question: "How often is the scholarship list updated?",
    answer:
      "Our team reviews and refreshes listings regularly. Once connected to a live backend, updates will happen automatically as providers publish new opportunities.",
  },
  {
    question: "Can I apply to a scholarship directly on ScholarNaija?",
    answer:
      "ScholarNaija is a discovery and tracking platform. When you're ready to apply, we link you directly to the official provider's application portal.",
  },
  {
    question: "What does 'Fully Funded' mean?",
    answer:
      "A Fully Funded scholarship covers tuition plus most or all additional costs — typically living expenses, flights, and health insurance. Always confirm exact coverage on the provider's official page.",
  },
  {
    question: "How does the AI Scholarship Matcher work?",
    answer:
      "You answer a few quick questions about your academic background and goals, and the matcher suggests scholarships that fit your profile, along with a match score. This is currently a UI preview using sample logic.",
  },
  {
    question: "I'm having trouble with my account. Who can I contact?",
    answer:
      "Reach out via the Contact link in our footer, or email our support team — we typically respond within 48 hours.",
  },
];

export const testimonials = [
  {
    name: "Amaka O.",
    role: "Chevening Scholar, 2025 Cohort",
    quote:
      "ScholarNaija helped me discover Chevening months before I would have found it on my own, and the deadline tracker kept me on schedule.",
  },
  {
    name: "Tunde A.",
    role: "MSc Student, University of Toronto",
    quote:
      "The filters made it so easy to narrow down scholarships that actually matched my engineering background.",
  },
  {
    name: "Blessing E.",
    role: "PhD Candidate, Cambridge",
    quote:
      "I loved how organized everything was — from eligibility to required documents, all in one place.",
  },
];
